-- 데이터 베이스 초기화
-- 스프링 부트는 SQL 스크립트를 실행하여 애플리케이션 로딩 시점에 데이터베이스를 초기화하는 기능 제공
-- 위치 : src/test/resources, 이름 : schema.sql -> 이름도 맞아야 한다
drop table if exists item CASCADE;
create table item
(
    id  bigint generated by default as identity,
    item_name varchar(10),
    price integer,
    quantity integer,
    primary key (id)
)